$(document).ready(()=>{
    if(!localStorage.getItem('style')){
        if(document.getElementById('dark').disabled){
            localStorage.setItem('style','light');
        }else{
            localStorage.setItem('style','dark');
        }
    }else{
        if(localStorage.getItem('style')=='light'){
            document.getElementById('light').disabled=false;
            document.getElementById('dark').disabled=true;
        }else{
            document.getElementById('light').disabled=true;
            document.getElementById('dark').disabled=false;
        }
    }
    $('.change_color').on('click',()=>{
        if(localStorage.getItem('style')=='dark'){
            document.getElementById('light').disabled=false;
            document.getElementById('dark').disabled=true;
            localStorage.setItem('style','light');
        }else{
            document.getElementById('light').disabled=true;
            document.getElementById('dark').disabled=false;
            localStorage.setItem('style','dark');
        }
    })
})